version: '3'

services:
  backend:
    user: "1000:1000"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # - type: volume
      #   source: media
      #   target: /usr/src/app/media
      # - type: volume
      #   source: common_static
      #   target: /usr/src/app/common_static
      - ./media:/usr/src/app/media
      - ./common_static:/usr/src/app/common_static
  frontend:
    user: "1000:1000"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      -  backend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/usr/src/app/frontend
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - API_HOST=localhost
      - API_PORT=8000