version: '3'

services:
  backend:
    user: "1000:1000"
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "python3.8 manage.py collectstatic --no-input &&
               gunicorn diplom.wsgi:application -b 0.0.0.0:8000 --reload"
    volumes:
      - ./:/usr/src/app

  frontend:
    user: "1000:1000"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      -  backend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/usr/src/app/frontend
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - API_HOST=localhost
      - API_PORT=8000

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on: 
      - backend
      - frontend
    ports: 
      - "8000:80"
    volumes:
      - ./static/:/static
      - ./media/:/media
      - ./common_static/:/common_static