# Generated by Django 3.1.7 on 2021-03-24 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_table_food_establishment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodestablishment',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='food_establishments', to=settings.AUTH_USER_MODEL),
        ),
    ]
