# Generated by Django 3.1.7 on 2021-03-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210324_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodestablishment',
            name='cousine',
            field=models.CharField(choices=[('BY', 'Национальная'), ('RU', 'Русская'), ('FR', 'Французская'), ('I', 'Итальянская'), ('CN', 'Китайская'), ('KR', 'Корейская')], default='BY', max_length=2),
        ),
    ]
