# Generated by Django 3.1.7 on 2021-03-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_foodestablishment_cousine'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodestablishment',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Количество посещений'),
        ),
    ]
