# Generated by Django 3.1.7 on 2021-03-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210325_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodestablishment',
            name='average_check',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Средний чек'),
        ),
    ]
