# Generated by Django 3.1.7 on 2021-03-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_foodestablishment_average_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodestablishment',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=2, null=True, verbose_name='Рейтинг'),
        ),
    ]
