# Generated by Django 3.1.7 on 2021-03-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210330_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodestablishment',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
    ]
