# Generated by Django 3.1.7 on 2021-03-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_foodestablishment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodestablishment',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
    ]
