# Generated by Django 3.1.7 on 2021-03-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210331_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodestablishment',
            old_name='logo',
            new_name='big_image',
        ),
        migrations.AddField(
            model_name='foodestablishment',
            name='closing_time',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='foodestablishment',
            name='opening_time',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
