# Generated by Django 3.1.7 on 2021-04-26 07:05

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210402_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodestablishment',
            name='number_of_tables',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.guest'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Номер телефона'),
        ),
    ]
