# Generated by Django 3.1.7 on 2021-04-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210426_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestfoodestablishmentm2m',
            name='number_of_visits',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Количество посещений'),
        ),
    ]
