# Generated by Django 3.1.7 on 2021-04-28 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210426_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='food_establishment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='core.foodestablishment'),
        ),
    ]
