# Generated by Django 3.1.7 on 2021-04-28 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210428_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='number_of_seats',
        ),
        migrations.RemoveField(
            model_name='table',
            name='status',
        ),
        migrations.AddField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.table'),
        ),
    ]
