# Generated by Django 3.1.7 on 2021-04-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_table_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='table',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер стола'),
        ),
    ]
