# Generated by Django 3.1.7 on 2021-05-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210503_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('ACT', 'Активна'), ('COM', 'Завершена'), ('CAN', 'Отменена')], default='ACT', max_length=3, verbose_name='Статус'),
        ),
    ]
