# Generated by Django 3.1.7 on 2021-05-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210515_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodestablishment',
            name='reservation_time',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Время бронирования'),
        ),
    ]
