# Generated by Django 3.1.7 on 2021-05-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_foodestablishment_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodestablishment',
            name='cousine',
            field=models.CharField(choices=[('BY', 'Национальная'), ('RU', 'Русская'), ('FR', 'Французская'), ('I', 'Итальянская'), ('CN', 'Китайская'), ('KR', 'Корейская'), ('PA', 'Паназиатская')], default='BY', max_length=2, verbose_name='Кухня'),
        ),
        migrations.AlterField(
            model_name='foodestablishment',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Описание'),
        ),
    ]
