# Generated by Django 3.1.7 on 2021-05-25 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210525_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodEstablismentGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
            ],
        ),
        migrations.RemoveField(
            model_name='foodestablishment',
            name='big_image',
        ),
        migrations.AddField(
            model_name='foodestablishment',
            name='table_layout',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Схема расположения столиков'),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.AddField(
            model_name='foodestablismentgallery',
            name='food_establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.foodestablishment'),
        ),
    ]
