# Generated by Django 3.1.7 on 2021-05-25 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210525_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='image',
        ),
        migrations.AlterField(
            model_name='foodestablismentgallery',
            name='food_establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.foodestablishment'),
        ),
    ]
